pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/omurdos/PMS.git'
            }
        }
        
        stage('Restore Packages') {
            steps {
                bat 'dotnet restore'
            }
        }
        
        stage('Build') {
            steps {
                 bat 'dotnet build --configuration Release'
            }
        }
        
        stage('Test') {
            steps {
                bat 'dotnet test --configuration Release'
            }
        }
        
        stage('Publish') {
            steps {
                 bat 'dotnet publish --configuration Release --output ./publish'
            }
        }
        
    }
    
}
